spring:
  application:
    name: demo

server:
  port: 8080

com:
  swj:
    k8sServiceIp: 127.0.0.1:8080

scanPackage:
  com.swj.api.demo

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health","prometheus"]
  metrics:
    export:
      prometheus:
        enabled: true